version: 2
jobs:
  build-job-and-deploy:
    docker:
      - image: circleci/node

    environment:
     - NODE_ENV: "production"

    working_directory: ~/tmp

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
           sudo apt-get update && sudo apt-get install -y python-dev
           curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
           unzip awscli-bundle.zip
           sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

#      - restore_cache:
#          name: Download and cache dependencies
#          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: npm install
          command: sudo npm install

#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - node_modules

      - run: sudo npm run build

      - run:
          name: Configure AWS
          command: |
            aws configure set default.region us-east-2
            aws configure set region us-east-2
            aws configure set preview.cloudfront true
            aws configure set preview.create-invalidation true

      - run:
          name:  Sync folder/files s3
          command: |
            pwd
            ls -a ~
            aws s3 sync ~/tmp/build s3://web.hiphopscoreboard.com --delete
            aws s3 sync ~/tmp/build s3://www.hiphopscoreboard.com --delete

      - run:
          name: Trigger CDN invalidation for web.hiphopscoreboard.com and www.hiphopscoreboard.com
          command: |
            aws cloudfront create-invalidation --invalidation-batch "{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}" --distribution-id E3RIU72B7OZJRL
            aws cloudfront create-invalidation --invalidation-batch "{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}" --distribution-id E1M8PK1KN3UF5G

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job-and-deploy:
          filters:
            branches:
              only: develop